### ISSUE TITLE
Only showing last location

### ISSUE THREAD

**Issue by benjaminchodroff** [owntracks/frontend#36] opened 2020-05-14 01:07 UTC
As of 2.3.1 (running in docker) I am only seeing the last data point and the history/heatmap features are no longer working. I can confirm the recorder app is still able to show historical data. There are no javascript errors in the console (other than a missing config.js). Anyone else facing similar issue?

**Comment by linusg** [comment] 2020-05-14 11:15
Still working fine for me. Double check your active layer settings, check what requests are made, try if the output of verbose mode gives you some clues. Or at least mention what version you were running before that.

Closing for now, feel free to reopen if you can provide more information.

**Closed by linusg** 2020-05-14 11:15 UTC

**Comment by benjaminchodroff** [comment] 2020-05-15 07:04
Thanks for your help!
owntracks/frontend (2.3.1) in docker latest
owntracks/recorder (0.8.6) in docker latest

Apologies, how do I enable verbose mode when using docker? 

I enabled all options (heatmap,last,line,points) in layer settings and I can see the following in the logs. I can't seem to spot any issues. When I click Download, I can easily see all the data points listed. 

2020-05-15 02:52:10 | stdout | 172.17.0.1 - - [15/May/2020:02:52:10 +0000] "GET /api/0/last HTTP/1.1" 200 463 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
-- | -- | --
2020-05-15 02:52:10 | stdout | 172.17.0.1 - - [15/May/2020:02:52:10 +0000] "GET /api/0/last HTTP/1.1" 200 463 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:10 | stdout | 172.17.0.1 - - [15/May/2020:02:52:10 +0000] "GET /api/0/version HTTP/1.1" 200 64 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:10 | stdout | 172.17.0.1 - - [15/May/2020:02:52:10 +0000] "GET /api/0/locations?from=2020-04-14T16%3A00%3A00&to=2020-05-15T15%3A59%3A59&user=benjaminchodroff&device=5e80857e-2da1-43ff-bbbf-d3c4eaeedd2d&format=json HTTP/1.1" 200 119987 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:10 | stdout | 172.17.0.1 - - [15/May/2020:02:52:10 +0000] "GET /api/0/locations?from=2020-04-14T16%3A00%3A00&to=2020-05-15T15%3A59%3A59&user=zhenggao&device=260dbb04-049e-42c7-a4e7-75dd3bb0343a&format=json HTTP/1.1" 200 31369 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /api/0/last HTTP/1.1" 200 463 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /favicon.ico HTTP/1.1" 200 1150 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /api/0/list?user=benjaminchodroff HTTP/1.1" 200 83 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /api/0/list?user=zhenggao HTTP/1.1" 200 82 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /api/0/list HTTP/1.1" 200 74 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /config/config.js HTTP/1.1" 500 580 "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 2020/05/15 02:52:09 [error] 9#9: *86 rewrite or internal redirection cycle while internally redirecting to "/config/config.js/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html", client: 172.17.0.1, server: , request: "GET /config/config.js HTTP/1.1", host: "server", referrer: "https://server/?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /ws/last HTTP/1.1" 101 858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-15 02:52:09 | stdout | 172.17.0.1 - - [15/May/2020:02:52:09 +0000] "GET /?lat=31.24537918348163&lng=121.4727830886841&zoom=16&start=2020-04-14T16%3A00%3A00&end=2020-05-15T15%3A59%3A59&layers=heatmap,last,line,points HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

**Comment by benjaminchodroff** [comment] 2020-05-16 00:44
I have reverted the container first to 2.3.0 (broken) and then to 2.2.0 (fixed) with the same data from the recorder. I was able to confirm the issue only gets fixed when I go back to owntracks-frontend v2.2.0. This is definitely a bug, but I'm not well versed enough in javascript to explain why it is happening - there are no errors in the log or in the browser console.

**Comment by bradeales** [comment] 2020-05-16 05:42
I'm hitting this issue as well.

**Comment by benjaminchodroff** [comment] 2020-05-16 06:35
@linusg I am unable to re-open this issue. Thanksfully, @bradeales has confirmed I'm not the only person seeing this issue. I do think this requires more investigation and I'm willing to help provide any further data to assist. I could also make my server temporarily public if you are willing to investigate it further (really wish I could password protect the site and backend natively!)

**Comment by ckrey** [comment] 2020-05-16 07:05
@linusg there seems to be typo here:

```
git diff
diff --git a/src/store/actions.js b/src/store/actions.js
index 227bcdf..4e41b1d 100644
--- a/src/store/actions.js
+++ b/src/store/actions.js
@@ -130,7 +130,7 @@ const _getDistanceTravelled = locationHistory => {
       let lastLatLng = null;
       locationHistory[user][device].forEach(location => {
         if (
-          config.minAccurac !== null &&
+          config.filters.minAccuraccy !== null &&
           location.acc > config.filters.minAccuracy
         )
           return;
diff --git a/src/store/getters.js b/src/store/getters.js
index d1857ce..5e1cdd8 100644
--- a/src/store/getters.js
+++ b/src/store/getters.js
@@ -19,7 +19,7 @@ const filteredLocationHistory = state => {
       locationHistory[user][device] = [];
       state.locationHistory[user][device].forEach(location => {
         if (
-          config.minAccurac !== null &&
+          config.filters.minAccuracy !== null &&
           location.acc > config.filters.minAccuracy
         )
           return;
```

**Comment by linusg** [comment] 2020-05-16 12:44
> @linusg there seems to be typo here:

Indeed, thanks. Will fix that. BUT this change wasn't even part of the 2.3.0 or 2.3.1 release https://github.com/owntracks/frontend/compare/v2.2.0...v2.3.1

@benjaminchodroff @bradeales the only way you could be running this code in production already is if you built your own image or are using the `latest` tag, **which is strongly discouraged**, not only here but in general.

**Comment by benjaminchodroff** [comment] 2020-05-16 13:22
Thanks for the fix. Glad we could help spot it. Loving this project - I
really enjoy the capability for my own personal use.

I’m not building the image myself, and pretty certain the issue was present
in the 2.3.0 and 2.3.1 dockerhub images I pulled. I am open to feedback on
this because I’m still learning, but isn’t “latest” commonly used by many
new people to a project to find/update to the projects stable docker image?
Latest does not actually become the latest image pushed - it’s just the one
that is not tagged - which is both dangerous (accidents happen too easily!)
and simultaneously useful. Right or wrong, the “latest” antipattern seems
to have gone mainstream thanks to watchtower and other similar projects.
I’d suggest ensuring all development builds get tagged in the pipeline to
avoid an untested release being set as latest prematurely. Please correct
me if I am mistaken!

**Comment by linusg** [comment] 2020-05-16 13:36
> I’m still learning, but isn’t “latest” commonly used by many
new people to a project to find/update to the projects stable docker image?
Latest does not actually become the latest image pushed - it’s just the one
that is not tagged - which is both dangerous (accidents happen too easily!)
and simultaneously useful.

Indeed - it's ambiguous and that should make it a no-go for anyone looking to do more than just some quick testing. It differs for each project of course but you can end up having just the "latest" stable release or the "latest" commit available from master (like here). (https://vsupalov.com/docker-latest-tag/, https://blog.container-solutions.com/docker-latest-confusion)

> I’d suggest ensuring all development builds get tagged in the pipeline to
avoid an untested release being set as latest prematurely

Yes, that'd be ideal - but I don't actually have access to this project's Docker Hub account, so it's not something I could configure :slightly_smiling_face: (cc @jpmens)

**Comment by bradeales** [comment] 2020-05-18 04:48
Thanks @linusg for responding on a closed ticket! I was also pulling dockerhub "latest", thinking it was master/stable based on convention. Issue is also present on 2.3.0, and 2.3.1 dockerhub images as far as I can tell.

FYI, I also see it has trouble plotting ancient owntracks data, even though it's visible in the recorder app.

**Comment by linusg** [comment] 2020-05-18 07:52
> Issue is also present on 2.3.0, and 2.3.1 dockerhub images as far as I can tell.

I'm still not believing that until someone can prove it to me. Again, the actual code changes in 2.3.0/1 are trivial and only add custom options for `fetch()`, and the dependency upgrades should not affect the map either - in fact, here's a screenshot of me running 2.3.1 via Docker:
 
![image](https://user-images.githubusercontent.com/19366641/82187776-d44cf480-98e4-11ea-80ee-5bf4ccba8d9e.png)

All layers working as intended.

> FYI, I also see it has trouble plotting ancient owntracks data, even though it's visible in the recorder app.

I don't know what you mean by that - if you feel like that's a bug, please open a separate issue providing the necessary details.

**Comment by benjaminchodroff** [comment] 2020-05-18 12:25
https://location.benchodroff.com:8443/

Please feel free to test with my instance

**Comment by benjaminchodroff** [comment] 2020-05-18 12:30
To compare, you can see 2.2.0 with the same data here:
https://location220.benchodroff.com:8443/

**Comment by linusg** [comment] 2020-05-18 17:01
Hi @benjaminchodroff,

thank you very much. I can indeed see the same bug in your deployed version by inspecting the source maps:

![image](https://user-images.githubusercontent.com/19366641/82238936-f15ae500-992f-11ea-98b1-1c201da057be.png)

I then took the `owntracks/frontend:v2.3.1` image and inspected it:

```
docker save owntracks/frontend:v2.3.1 | gzip > frontend.tar.gz
mkdir frontend
tar -xvzf frontend.tar.gz -C frontend
cd frontend/5d7b502b9889781f20060ad7051995f25c8d6be1c11aceb61d09205d334b0781/
tar -xvf layer.tar
cd usr/share/nginx/html/js
```

At that point we can again inspect the source maps:

```
grep Acc app.73109ba2.js.map
```

No result - the code you're running is not in that image.

So even though it says "2.3.1" on your version, I suspect that it isn't actually the image tagged with `v2.3.1` but `latest` - it will contain the last released version number until the next release is published. Hope that clears things up.

**Comment by benjaminchodroff** [comment] 2020-05-19 02:31
Thanks for helping get to the bottom of this! Yes, it seems the issue is
related to the latest tag image only and hopefully the next release clears
the bug up.
