### ISSUE TITLE
Container just constantly restarts

### ISSUE THREAD

**Issue by 0x6b-dev** [owntracks/frontend#69] opened 2022-02-15 12:30 UTC
Ran the docker compose, mapped the config file - container just restarts constantly.

2022/02/15 12:25:43 [emerg] 8#8: host not found in upstream "otrecorder:8083" in /etc/nginx/nginx.conf:7
nginx: [emerg] host not found in upstream "otrecorder:8083" in /etc/nginx/nginx.conf:7

**Comment by jpmens** [comment] 2022-02-15 12:43
duplicate of https://github.com/owntracks/recorder/issues/376 ?

**Comment by jpmens** [comment] 2022-02-15 12:44
I think you'll need to show us that configuration for us to see what's going on

**Comment by linusg** [comment] 2022-02-15 14:41
> Copy paste compose file.

The compose file from the README is not functional on its own. It requires another service named `otrecorder`, for which noo config can be provided as it differers for every setup. This is being mentioned in the README:

> if you also run the OwnTracks Recorder with the default compose config, and the service is named otrecorder

---

> Do I require the recorder?

Yes, obviously. Where else would the data come from?

---

> Copy public/config - where? Where is this folder?

This is the file that is being mapped into the container like this:

```yaml
- ./path/to/custom/config.js:/usr/share/nginx/html/config/config.js
```

The contents of the directory `public` in the repo is being copied into `/usr/share/nginx/html` in the container.

The root cause of the restart is the recorder not running or being reachable, which has nothing to do with the frontend - once you resolve that issue, it should work.

**Closed by linusg** 2022-02-15 14:41 UTC
