### ISSUE TITLE
Improvement: Selection of Settings

### ISSUE THREAD

**Issue by cocker-cc** [owntracks/frontend#101] opened 2023-06-10 08:49 UTC
Assume I have a **huge** amount of Data, and I want to visualize a particular Day in the Past.  First I have to select the older Timestamp, which instantly loads **all** the Data from this old Timestamp up to today.  This is very time-consuming and heavily challenges the CPU.

The Improvement would be: Let the User specify all the needed Settings without loading the Data in the Meantime.

**Comment by linusg** [comment] 2023-06-10 10:54
Duplicate of #43.

**Closed** 2023-06-10 10:54 UTC
